;;; Searchable plant manager. Callback state is local to each dialog invocation.
(setq *TT:PlantUIModuleLoaded* T)

(defun TT:PlantUIString (value)
  (cond ((eq (type value) 'STR) value) ((numberp value) (rtos value 2 4)) (T "")))

(defun TT:PlantUISelected ()
  (if (and visible (> (length visible) 0)) (nth (atoi (get_tile "plants")) visible)))

(defun TT:PlantUIDetails (/ record source description)
  (setq record (TT:PlantUISelected))
  (if record
    (progn
      (set_tile "name" (TT:PlantUIString (TT:DataValue record 'BOTANICAL_NAME)))
      (setq source (if (TT:DataValue record 'PROJECT_PLANT_ID)
                      (TT:PlantProjectSourceStatus record)
                      (if (TT:DataValue record 'DATABASE_SUMMARY) "WFO | CC0 | Taxonomy only"
                          (TT:PlantUIString (TT:DataValue record 'SOURCE)))))
      (set_tile "source" source)
      (setq description (TT:PlantUIString (TT:DataValue record 'GENERATED_DESCRIPTION)))
      (set_tile "description" (substr description 1 88)))
    (progn (set_tile "name" "No plant selected.") (set_tile "source" "") (set_tile "description" ""))))

(defun TT:PlantUIPage (/ record key)
  (setq visible (TT:PlantPage results page 30))
  (start_list "plants")
  (foreach record visible (add_list (TT:PlantSearchLabel record)))
  (end_list)
  (set_tile "plants" "0")
  (set_tile "page" (strcat "Page " (itoa (1+ page)) " | " (itoa (length results)) " result(s)"))
  (mode_tile "previous" (if (> page 0) 0 1))
  (mode_tile "next" (if (< (* (1+ page) 30) (length results)) 0 1))
  (foreach key '("add" "variant" "edit" "remove" "favorite" "place" "details")
    (mode_tile key (if visible 0 1)))
  (mode_tile "edit" (if (and visible (= mode 0)) 0 1))
  (mode_tile "remove" (if (and visible (= mode 0)) 0 1))
  (mode_tile "add" (if (and visible (/= mode 0)) 0 1))
  (TT:PlantUIDetails))

(defun TT:PlantUIRefresh (/ query category index all item ids id)
  (setq query (get_tile "query") mode (atoi (get_tile "mode"))
        index (atoi (get_tile "category")) category (if (> index 0) (nth (1- index) *TT:PlantCategories*))
        page 0 project (TT:ProjectCurrent))
  (if (= mode 0)
    (progn
      (setq all (TT:PlantPaletteGetAllFromPalette (TT:PlantPaletteLoad)) results nil)
      (foreach item all
        (if (TT:PlantSearchMatchesP (cons item (TT:PlantSearchText item))
              (TT:StringWords query) category nil nil)
          (setq results (cons item results))))
      (setq results (reverse results)))
    (if (member mode '(2 3))
      (progn
        (setq ids (if project (TT:ProjectValue project (if (= mode 2) 'PLANT_FAVORITES 'PLANT_RECENT))) results nil)
        (foreach id ids
          (if (setq item (TT:PlantMasterFindByID id))
            (if (TT:PlantSearchMatchesP (cons item (TT:PlantSearchText item))
                  (TT:StringWords query) category nil nil)
              (setq results (cons item results)))))
        (setq results (reverse results)))
      (progn
        (set_tile "status" "Searching local catalogs...")
        (setq results (TT:PlantSearch query category nil))
        (if (or (null category) (eq category 'OTHER))
          (setq results (append results (TT:PlantDatabaseSearch query)))))))
  (set_tile "status"
    (cond ((and (= mode 0) (null results)) "No project plants. Choose Plant Sources, search, then Add to Project.")
          ((and (/= mode 0) (< (strlen query) 2)) "Open database search needs at least two letters. Sample/user plants are shown.")
          ((>= (length results) 500) "First 500 open database matches shown. Narrow the search for more precise results.")
          ((null results) "No matches. Try a shorter name or All categories.")
          (T "Project edits are independent of source catalogs.")))
  (TT:PlantUIPage))

(defun TT:PlantUIEditAccept (/ value cost pair)
  (setq value (get_tile "cost") cost (if (= value "") "" (TT:StrictDecimal value)))
  (cond
    ((= (vl-string-trim " " (get_tile "code")) "") (set_tile "error" "Enter a project plant code."))
    ((or (null cost) (and (numberp cost) (< cost 0.0))) (set_tile "error" "Unit cost must be nonnegative or blank."))
    (T
      (setq edited (TT:DataPut edit-record 'PLANT_CODE (vl-string-trim " " (get_tile "code"))))
      (foreach pair '(("size" . SIZE) ("spacing" . SPACING) ("symbol" . SYMBOL_BLOCK) ("notes" . NOTES))
        (setq edited (TT:DataPut edited (cdr pair) (get_tile (car pair)))))
      (setq edited (TT:DataPut edited 'UNIT_COST cost)
            edited (TT:DataPut edited 'CATEGORY (nth (atoi (get_tile "category")) *TT:PlantCategories*)))
      (if (TT:PlantPaletteRecordValidate edited) (done_dialog 1)
        (set_tile "error" (TT:PlantLastError))))))

(defun TT:PlantUIEditRecord (edit-record / dialog-id edited index pair category)
  (setq dialog-id (load_dialog (TT:StorageJoinPath *TT:Root* "dialogs/terratools-plants.dcl")))
  (if (and (> dialog-id 0) (new_dialog "terratools_plant_edit" dialog-id))
    (progn
      (set_tile "plant_name" (TT:DataValue edit-record 'BOTANICAL_NAME))
      (foreach pair '(("code" . PLANT_CODE) ("size" . SIZE) ("spacing" . SPACING)
                      ("cost" . UNIT_COST) ("symbol" . SYMBOL_BLOCK) ("notes" . NOTES))
        (set_tile (car pair) (TT:PlantUIString (TT:DataValue edit-record (cdr pair)))))
      (start_list "category") (foreach category *TT:PlantCategories* (add_list (TT:PlantCategoryName category))) (end_list)
      (setq index (vl-position (TT:DataValue edit-record 'CATEGORY) *TT:PlantCategories*))
      (set_tile "category" (itoa (if index index 9)))
      (action_tile "accept" "(TT:PlantUIEditAccept)")
      (action_tile "cancel" "(setq edited nil)(done_dialog 0)")
      (start_dialog)))
  (if (> dialog-id 0) (unload_dialog dialog-id))
  edited)

(defun TT:PlantPaletteCodeExistsP (plants code except-id / found plant)
  (foreach plant plants
    (if (and (equal (strcase code) (strcase (TT:DataValue plant 'PLANT_CODE)))
             (not (equal except-id (TT:DataValue plant 'PROJECT_PLANT_ID)))) (setq found T)))
  found)

(defun TT:PlantPaletteStoreRecord (record old / palette plants)
  (setq palette (TT:PlantPaletteLoad) plants (TT:PlantPaletteGetAllFromPalette palette))
  (cond ((null palette) nil)
    ((TT:PlantPaletteCodeExistsP plants (TT:DataValue record 'PLANT_CODE) (TT:DataValue record 'PROJECT_PLANT_ID))
      (princ "\nThat project code already exists. Use a distinct code for each variant.") nil)
    (T (TT:PlantPaletteSave (TT:PlantPaletteWithPlants palette
         (if old (subst record old plants) (append plants (list record))))))))

(defun TT:PlantRecordReferencedP (id project / found item mix component)
  (foreach item (TT:SmartScan)
    (if (equal id (cdr (assoc 'CATALOG_ID (cdr item)))) (setq found T)))
  (foreach mix (TT:ProjectValue project 'PLANT_MIXES)
    (foreach component (TT:DataValue mix 'COMPONENTS)
      (if (equal id (TT:DataValue component 'PROJECT_PLANT_ID)) (setq found T))))
  found)

(defun TT:PlantUIAction (action selected / record old project point palette answer pair)
  (setq project (TT:ProjectCurrent) record (TT:PlantResolveSummary selected))
  (cond
    ((= action 8) (C:TTPLANTUSER))
    ((null record) (princ "\nThe selected source is unavailable. Reload its catalog and try again."))
    ((= action 7)
      (TT:UIRecordDetails record))
    ((null project) (princ "\nOpen a project before changing its plant palette."))
    ((= action 5)
      (TT:PlantToggleFavorite (TT:DataPut record 'PLANT_ID
        (if (TT:DataValue record 'PROJECT_PLANT_ID) (TT:DataValue record 'MASTER_PLANT_ID) (TT:DataValue record 'PLANT_ID)))))
    ((member action '(1 2 3))
      (setq old (if (= action 3) record))
      (if (not (TT:DataValue record 'PROJECT_PLANT_ID)) (setq record (TT:PlantProjectRecordFromMaster record)))
      (if (= action 2) (setq record (TT:DataPut record 'PROJECT_PLANT_ID (TT:GenerateUUID))
                            record (TT:DataPut record 'PLANT_CODE (strcat (TT:DataValue record 'PLANT_CODE) "-V"))))
      (if (setq record (TT:PlantUIEditRecord record))
        (if (TT:PlantPaletteStoreRecord record old)
          (progn (TT:PlantRememberRecent (TT:DataValue record 'MASTER_PLANT_ID)) (princ "\nProject plant saved.")))))
    ((= action 4)
      (if (TT:PlantRecordReferencedP (TT:DataValue record 'PROJECT_PLANT_ID) project)
        (princ "\nThis plant is used by drawing objects or a mix. Replace those uses before removing it. Other DWGs must also be checked.")
        (progn
          (initget "Yes No") (setq answer (getkword "\nRemove project plant? Check other project DWGs first. [Yes/No] <No>: "))
          (if (= answer "Yes")
            (progn (setq palette (TT:PlantPaletteLoad))
              (TT:PlantPaletteSave (TT:PlantPaletteWithPlants palette
                (vl-remove record (TT:PlantPaletteGetAllFromPalette palette)))))))))
    ((= action 6)
      (if (not (TT:DataValue record 'PROJECT_PLANT_ID))
        (princ "\nAdd this plant to the project before placing it.")
        (progn
          (command-s "_.UNDO" "_Begin")
          (while (setq point (getpoint "\nPlant point <finish>: "))
            (TT:PlantCreateInstance project record (trans point 1 0) nil))
          (command-s "_.UNDO" "_End"))))))

(defun TT:PlantManager (initial-mode / *error* dialog-id mode project results visible page record pair key selected action done category saved-query saved-category)
  (defun *error* (message)
    (if (and dialog-id (> dialog-id 0)) (unload_dialog dialog-id))
    (if (= 8 (logand 8 (getvar "UNDOCTL"))) (command-s "_.UNDO" "_End"))
    (TT:ReportError "Plant Manager" message))
  (setq mode initial-mode action 1 saved-query "" saved-category "0")
  (while (> action 0)
    (setq dialog-id (load_dialog (TT:StorageJoinPath *TT:Root* "dialogs/terratools-plants.dcl")))
    (if (and (> dialog-id 0) (new_dialog "terratools_plants" dialog-id))
      (progn
        (setq project (TT:ProjectCurrent))
        (set_tile "context" (strcat "TerraTools LT " *TT:Version* " | "
          (if project (TT:ProjectValue project 'PROJECT_NAME) "No active project. Search is available.")))
        (start_list "mode") (mapcar 'add_list '("Project Plants" "Plant Sources" "Favorites" "Recent Plants")) (end_list)
        (set_tile "mode" (itoa mode))
        (set_tile "query" saved-query)
        (start_list "category") (add_list "All categories")
        (foreach category *TT:PlantCategories* (add_list (TT:PlantCategoryName category))) (end_list)
        (set_tile "category" saved-category)
        (action_tile "search" "(TT:PlantUIRefresh)")
        (action_tile "mode" "(TT:PlantUIRefresh)")
        (action_tile "category" "(TT:PlantUIRefresh)")
        (action_tile "plants" "(TT:PlantUIDetails)")
        (action_tile "previous" "(setq page (1- page))(TT:PlantUIPage)")
        (action_tile "next" "(setq page (1+ page))(TT:PlantUIPage)")
        (foreach pair '(("add" . 1) ("variant" . 2) ("edit" . 3) ("remove" . 4)
                        ("favorite" . 5) ("place" . 6) ("details" . 7) ("user" . 8))
          (action_tile (car pair) (strcat "(setq selected (TT:PlantUISelected) saved-query (get_tile \"query\") saved-category (get_tile \"category\"))(done_dialog " (itoa (cdr pair)) ")")))
        (action_tile "cancel" "(done_dialog 0)")
        (TT:PlantUIRefresh)
        (setq action (start_dialog)) (unload_dialog dialog-id) (setq dialog-id nil done T)
        (if (> action 0) (TT:PlantUIAction action selected)))
      (progn (if (> dialog-id 0) (unload_dialog dialog-id)) (setq dialog-id nil action 0))))
  done)

(defun C:TTPLANTS () (if (not (TT:PlantManager 0)) (C:TTPLANTSCLI)) (princ))
(defun C:TTPLANTSEARCH () (if (not (TT:PlantManager 1)) (C:TTPLANTSEARCHCLI)) (princ))
T
