;;; Read-only graph fixtures. No entities, files, preferences or projects changed.
(defun TT:QAEdge (id a b)
  (list 'NETWORK_EDGE (cons 'EDGE_ID id) (cons 'START a) (cons 'END b)
    '(LENGTH_FT . 100.0) '(DATA (DIAMETER_IN . 1.0) (C_FACTOR . 150.0))))

(defun TT:QAEdgeFlow (graph id / edge)
  (setq edge (TT:DataFindByValue (TT:DataValue graph 'EDGES) 'EDGE_ID id))
  (cdr (assoc (TT:DataValue edge 'TO) (TT:DataValue graph 'FLOWS))))

(defun TT:QANetworkChecks (/ a b c d edges demands graph report checks single raised lowered merged looped disconnected multiple reversed third value)
  (setq a '(0.0 0.0 0.0) b '(10.0 0.0 0.0) c '(20.0 10.0 0.0) d '(20.0 -10.0 0.0)
        edges (list (TT:QAEdge 0 a b) (TT:QAEdge 1 b c) (TT:QAEdge 2 b d))
        demands (list (list c 2.0 30.0 0.0) (list d 3.0 40.0 0.0))
        graph (TT:NetworkBuild edges demands (list a) 0.001)
        report (TT:NetworkPressure graph 60.0 'FEET)
        single (TT:NetworkBuild (list (TT:QAEdge 0 a b)) (list (list b 10.0 30.0 0.0)) (list a) 0.001)
        checks (list
          (cons "Graph: single source and demand" (and (null (TT:DataValue single 'ERRORS)) (= (TT:QAEdgeFlow single 0) 10.0)))
          (cons "Graph: branch demand aggregation" (and (null (TT:DataValue graph 'ERRORS)) (= (TT:QAEdgeFlow graph 0) 5.0)))
          (cons "Graph: each edge uses downstream TO demand" (and (= (TT:QAEdgeFlow graph 1) 2.0) (= (TT:QAEdgeFlow graph 2) 3.0)))
          (cons "Graph: automatic critical path" (equal (TT:DataValue report 'CRITICAL_EDGE_IDS) '(0 2)))
          (cons "Graph: terminal pressure requirement" (> (TT:DataValue report 'SOURCE_REQUIRED_PSI) 40.0))))
  (setq third (TT:NetworkBuild (append edges (list (TT:QAEdge 3 b '(20.0 0.0 0.0))))
    (append demands '(((20.0 0.0 0.0) 7.0 20.0 0.0))) (list a) 0.001))
  (setq checks (cons (cons "Graph: three-terminal branch" (= (TT:QAEdgeFlow third 0) 12.0)) checks))
  (foreach value
    (list
      (list "merged paths" (append edges (list (TT:QAEdge 3 c d))) demands (list a))
      (list "directed loop" (append edges (list (TT:QAEdge 3 d b))) demands (list a))
      (list "disconnected demand" edges (append demands '(((99.0 99.0 0.0) 1.0 20.0 0.0))) (list a))
      (list "multiple sources" edges demands (list a b))
      (list "pipe into source" (list (TT:QAEdge 0 b a)) (list (list b 1.0 20.0 0.0)) (list a)))
    (setq single (TT:NetworkBuild (nth 1 value) (nth 2 value) (nth 3 value) 0.001)
          checks (cons (cons (strcat "Graph: reject " (car value))
            (and (TT:DataValue single 'ERRORS) (null (TT:NetworkPressure single 60.0 'FEET)))) checks)))
  (setq single (TT:NetworkBuild (list (TT:QAEdge 0 a b)) (list (list b 10.0 30.0 2.0)) (list a) 0.001)
        report (TT:NetworkPressure single 60.0 'FEET)
        checks (cons (cons "Pressure: friction plus inline loss"
          (TT:QAApprox (TT:DataValue report 'SOURCE_REQUIRED_PSI) 35.0155713291 1e-6)) checks))
  (foreach value '(10.0 -10.0)
    (setq b (list 10.0 0.0 value)
          single (TT:NetworkBuild (list (TT:QAEdge 0 a b)) (list (list b 0.0 30.0 0.0)) (list a) 0.001)
          report (TT:NetworkPressure single 60.0 'FEET)
          checks (cons (cons (if (> value 0) "Pressure: elevation rise" "Pressure: elevation drop")
            (TT:QAApprox (TT:DataValue report 'SOURCE_REQUIRED_PSI) (+ 30.0 (/ value 2.31)) 1e-8)) checks)))
  (reverse checks))

(defun TT:QAExtended (/ checks check passed value)
  (setq passed T checks (TT:QANetworkChecks))
  (setq checks (append checks (list
    (cons "Hydraulics: known friction psi" (TT:QAApprox (TT:FeetHeadToPSI (TT:HazenWilliamsHeadLossFT 100.0 10.0 1.0 150.0)) 3.0155713291 1e-6))
    (cons "Hydraulics: pressure/head round trip" (TT:QAApprox (TT:FeetHeadToPSI (TT:PSIToFeetHead 40.0)) 40.0 1e-9))
    (cons "Hydraulics: actual diameter overrides nominal" (= (TT:PipeInsideDiameter '((DIAMETER_IN . 1.0) (INSIDE_DIAMETER . 1.049))) 1.049))
    (cons "Units: reject repeated decimal" (null (TT:ParseDimension "1.2.3 ft")))
    (cons "Units: feet and inches" (equal (TT:ParseDimension "5' 6\"") '(5.5 FEET)))
    (cons "Geometry: containment" (and (TT:PointInPolygon '(5 5) '((0 0) (10 0) (10 10) (0 10)))
      (not (TT:PointInPolygon '(15 5) '((0 0) (10 0) (10 10) (0 10))))))
    (cons "Storage: reject trailing expression" (not (TT:StorageDataTextP "(A) (B)")))
    (cons "Search: multiword punctuation normalization" (equal (TT:PlantDatabaseSearchWords "Quercus, alba") '("QUERCUS" "ALBA")))
    (cons "Migration: reject unknown schema" (null (TT:ProjectCanMigrate '(TERRATOOLS_PROJECT (DATA_SCHEMA_VERSION . 99)) 1))))))
  (foreach check checks
    (if (not (TT:QALine (cdr check) (car check) "true" "false")) (setq passed nil)))
  passed)
T
