;;; TerraTools LT - Main DCL launcher and command-line module menus.

(setq *TT:UIModuleLoaded* T)

(defun TT:UIRunCommand (choice)
  (cond ((= choice 1) (C:TTPROJECT))
        ((= choice 2) (C:TTPREFERENCES))
        ((= choice 3) (C:TTWORKAREA))
        ((= choice 4) (C:TTPLANTING))
        ((= choice 5) (C:TTSITE))
        ((= choice 6) (C:TTDETAILS))
        ((= choice 7) (C:TTLIGHTING))
        ((= choice 8) (C:TTIRRIGATION))
        ((= choice 9) (C:TTSCHEDULES))
        ((= choice 10) (C:TTDIAGNOSTICS))
        ((= choice 11) (C:TTABOUT))))

(defun TT:MainDialog (/ path dialog-id choice result pair)
  (setq path (TT:StorageJoinPath (TT:StorageJoinPath *TT:Root* "dialogs")
                                 "terratools-main.dcl"))
  (if (and (findfile path) (> (setq dialog-id (load_dialog path)) 0)
           (new_dialog "terratools_main" dialog-id))
    (progn
      (foreach pair '(("project" . 1) ("settings" . 2) ("workareas" . 3)
                      ("planting" . 4) ("site" . 5) ("details" . 6)
                      ("lighting" . 7) ("irrigation" . 8) ("schedules" . 9)
                      ("diagnostics" . 10) ("about" . 11))
        (action_tile (car pair) (strcat "(done_dialog " (itoa (cdr pair)) ")")))
      (action_tile "close" "(done_dialog 0)")
      (setq choice (start_dialog))
      (unload_dialog dialog-id)
      (if (> choice 0) (TT:UIRunCommand choice))
      T)
    (progn
      (if (and dialog-id (> dialog-id 0)) (unload_dialog dialog-id))
      nil)))

(defun C:TT (/ *error* option)
  (defun *error* (message) (TT:ReportError "TT" message))
  (if (not (TT:MainDialog))
    (progn
      (princ "\nThe TerraTools dialog could not be opened. Using the command-line launcher.")
      (initget "Project Planting Site Details Lighting Irrigation Schedules Settings Diagnostics About")
      (setq option (getkword "\nTerraTools [Project/Planting/Site/Details/Lighting/Irrigation/Schedules/Settings/Diagnostics/About]: "))
      (cond ((equal option "Project") (C:TTPROJECT))
            ((equal option "Planting") (C:TTPLANTING))
            ((equal option "Site") (C:TTSITE))
            ((equal option "Details") (C:TTDETAILS))
            ((equal option "Lighting") (C:TTLIGHTING))
            ((equal option "Irrigation") (C:TTIRRIGATION))
            ((equal option "Schedules") (C:TTSCHEDULES))
            ((equal option "Settings") (C:TTPREFERENCES))
            ((equal option "Diagnostics") (C:TTDIAGNOSTICS))
            ((equal option "About") (C:TTABOUT)))))
  (princ))

(defun C:TERRATOOLS () (C:TT))

(defun C:TTPLANTING (/ option)
  (initget "Palette Place Areas Mix Labels Schedule Verify")
  (setq option (getkword "\nPlanting [Palette/Place/Areas/Mix/Labels/Schedule/Verify] <Palette>: "))
  (if (null option) (setq option "Palette"))
  (cond ((equal option "Palette") (C:TTPLANTS))
        ((equal option "Place") (C:TTPLACEPLANT))
        ((equal option "Areas") (C:TTGROUND))
        ((equal option "Mix") (C:TTMIX))
        ((equal option "Labels") (C:TTLABELGROUP))
        ((equal option "Schedule") (C:TTPLANTSCHEDULE))
        ((equal option "Verify") (C:TTVERIFYPLANTS)))
  (princ))

(defun C:TTSITE (/ option)
  (initget "Reference Area Length Volume Slope Coordinate Spot Concept Convert Schedule")
  (setq option (getkword "\nSite [Reference/Area/Length/Volume/Slope/Coordinate/Spot/Concept/Convert/Schedule]: "))
  (cond ((equal option "Reference") (C:TTREFNOTE)) ((equal option "Area") (C:TTAREA))
        ((equal option "Length") (C:TTLENGTH)) ((equal option "Volume") (C:TTVOLUME))
        ((equal option "Slope") (C:TTSLOPE)) ((equal option "Coordinate") (C:TTCOORDLABEL))
        ((equal option "Spot") (C:TTSPOTELEVATION)) ((equal option "Concept") (C:TTCONCEPT))
        ((equal option "Convert") (C:TTUNITCONVERT))
        ((equal option "Schedule") (C:TTREFNOTESCHEDULE)))
  (princ))

(defun C:TTSCHEDULES (/ option)
  (initget "Plants References Details Lighting Irrigation")
  (setq option (getkword "\nSchedules [Plants/References/Details/Lighting/Irrigation]: "))
  (cond ((equal option "Plants") (C:TTPLANTSCHEDULE))
        ((equal option "References") (C:TTREFNOTESCHEDULE))
        ((equal option "Details") (C:TTDETAILINDEX))
        ((equal option "Lighting") (C:TTLIGHTINGSCHEDULE))
        ((equal option "Irrigation") (C:TTIRRIGATIONSCHEDULE)))
  (princ))

(defun C:TTDIAGNOSTICS (/ option)
  (initget "Debug Smoke Verify Reconcile")
  (setq option (getkword "\nDiagnostics [Debug/Smoke/Verify/Reconcile] <Debug>: "))
  (if (null option) (setq option "Debug"))
  (cond ((equal option "Debug") (C:TTDEBUG)) ((equal option "Smoke") (C:TTDEVSMOKE))
        ((equal option "Verify") (C:TTVERIFY)) ((equal option "Reconcile") (C:TTRECONCILE)))
  (princ))

(defun C:TTABOUT (/ project)
  (setq project (TT:ProjectCurrent))
  (princ (strcat "\nTerraTools LT " *TT:Version*
                 "\nTarget: AutoCAD LT 2024+ on Windows"
                 "\nProject: " (if project (TT:ProjectValue project 'PROJECT_NAME) "None")
                 "\nModules: Planting, Site, Details, Lighting, Irrigation, Schedules"))
  (princ))

T
