;;; DEVELOPMENT ONLY: run after lt-regression.lsp in its disposable project.
(defun TT:CompletionRegression (/ regression-failures project copy classes report rows style path package record station controller)
  (setq regression-failures 0 project (TT:ProjectCurrent))
  (TT:RegressionAssert (equal (TT:ProjectMigrate project 1) project) "migration preserves current schema and unknown fields")
  (TT:RegressionAssert (TT:QAApprox (TT:DripAreaDemand 100.0 2.0 1.0 0.5) (/ 25.0 60.0) 1e-8) "drip emitter spacing")
  (setq classes '(PIPE_CLASS (SIZES_TEXT . "1:1.049 1.25:1.380") (C_FACTOR . 150.0)))
  (TT:RegressionAssert (equal (TT:PipeClassSizes classes) '((1.0 1.049) (1.25 1.38)) 1e-8) "actual inside-diameter pairs")
  (TT:RegressionAssert (null (TT:PipeClassSizes '(PIPE_CLASS (SIZES_TEXT . "1:bad")))) "reject malformed class")
  (setq rows '((SCHEDULE_ROW (CODE . "B") (QUANTITY . 2) (CATEGORY . TREE))
               (SCHEDULE_ROW (CODE . "A") (QUANTITY . 2) (CATEGORY . TREE))) style (TT:DefaultScheduleStyle))
  (TT:RegressionAssert (= (length (TT:ScheduleRowsSorted rows style)) 2) "schedule sorting preserves equal-valued rows")
  (TT:RegressionAssert (= (TT:DataValue (car (TT:ScheduleRowsSorted rows style)) 'CODE) "A") "schedule sorts by code")
  (TT:RegressionAssert (equal (TT:CSVParseLine "\"two\nlines\",\"ok\"") '("two\nlines" "ok")) "CSV quoted newline")
  (TT:RegressionAssert (null (TT:CSVParseLine "ab\"c,def")) "CSV rejects quotes in unquoted field")
  (TT:RegressionAssert (and (TT:PackageRelativePathP "resources/a.dwg")
    (not (TT:PackageRelativePathP "../outside.dwg")) (not (TT:PackageRelativePathP "C:/outside.dwg"))) "package traversal rejection")
  (setq controller '(IRRIGATION_CONTROLLERS (CONTROLLER_ID . "QA-C") (NAME . "QA Controller") (CAPACITY . 2) (DESCRIPTION . "Test")))
  (TT:RegressionAssert (TT:ManagerSaveRecord 'CONTROLLER controller nil) "controller persistence")
  (setq station '(IRRIGATION_STATIONS (STATION_ID . "QA-S") (NAME . "QA Station") (CONTROLLER . "QA Controller") (OUTPUT . 1) (NOTES . "Test")))
  (TT:RegressionAssert (TT:ManagerSaveRecord 'STATION station nil) "station assignment persistence")
  (TT:RegressionAssert (not (TT:ManagerSaveRecord 'STATION (TT:DataPut (TT:DataPut station 'STATION_ID "QA-S2") 'NAME "Second") nil)) "duplicate controller output rejected")
  (setq package (TT:StorageJoinPath (getenv "TEMP") (strcat "TTPackageQA-" (TT:GenerateUUID))))
  (TT:RegressionAssert (TT:PackageCreate package nil) "project package creation")
  (TT:RegressionAssert (TT:PackageOpen (TT:StorageJoinPath package "terratools-package.dat")) "package reopen")
  (TT:RegressionAssert (equal (TT:ProjectValue (TT:ProjectCurrent) 'PROJECT_UUID) (TT:ProjectValue project 'PROJECT_UUID)) "package project identity retained")
  (princ (strcat "\nCOMPLETION REGRESSION FAILURES: " (itoa regression-failures)))
  (princ))
(TT:CompletionRegression)
